### ISSUE TITLE
2 Suggestions

### ISSUE THREAD

**Issue by ojnc** [torifat/jsAvroPhonetic#14]
a) Assamese is included in Unicode Bangla range with only 2 differences
ৰ ৱ It may be nice if you extend phonetic map accordingly 

b) Bengali text in plain text tiny and unreadable esp on Windows Desktop On Android and iOS things are slightly better but not good enough 

Happens in Google as well as Facebook posts where plain text is only option

Hindi text in posts renders fine; easy to read.

Bengali/Bangla text is tiny and unreadable; very painful.

Example below

সঙ্কোচের বিহ্বলতা নিজেরে অপমান।
সঙ্কটের কল্পনাতে হোয়ো না ম্রিয়মাণ।
মুক্ত করো ভয়, আপনা-মাঝে শক্তি ধরো, নিজেরে করো জয়। দুর্বলেরে রক্ষা করো, দুর্জনেরে হানো, নিজেরে দীন নিঃসহায় যেন কভু না জানো। মুক্ত করো ভয়, নিজের 'পরে করিতে ভর না রেখো সংশয়। ধর্ম যবে শঙ্খরবে করিবে আহ্বান নীরব হয়ে নম্র হয়ে পণ করিয়ো প্রাণ। মুক্ত করো ভয়, দুরূহ কাজে নিজেরি দিয়ো কঠিন পরিচয়॥

सङ्कोचेर बिह्बलता निजेरे अपमान |
सङ्कटेर कल्पनाते होय़ो ना म्रिय़माण |
मुक्त करो भय़, आपना-माझे शक्ति धरो, निजेरे करो जय़ | दुर्बलेरे रक्षा करो, दुर्जनेरे हानो, निजेरे दीन निःसहाय़ येन कभु ना जानो | मुक्त करो भय़, निजेर 'परे करिते भर ना रेखो संशय़ | धर्म यबे शङ्खरबे करिबे आह्बान नीरब हय़े नम्र हय़े पण करिय़ो प्राण | मुक्त करो भय़, दुरूह काजे निजेरि दिय़ो कठिन परिचय़ ||

As you have done so much pioneering work
you may take this up with Google & Facebook & Microsoft

**Comment by ojnc** [comment]
Solved ....
Bengali text in posts tiny and unreadable in Windows Desktop
Does not look so bad in Android or iOS
Facebook and few others use plain text and default Windows font 
for Bangla/Assamese is the terrible Vrinda font (root cause of malady)

As usual Omicronlab (maker of Avro) has a solution
http://www.omicronlab.com/tools/font-fixer.html
http://www.omicronlab.com/blog/tips-and-tricks/how-to-use-font-fixer-tool-to-fix-broken-bangla-text/

I use SolaimanLipi from
https://code.google.com/p/bangla-pad/downloads/detail?name=SolaimanLipi.ttf 

In Fontfixer made SolaimanLipi the default for Bangla
Then Bangla facebook post read awfully nice

Please suggest to Microsoft to have a decent default font!

Thanks & Regards
-jnc

**Comment by torifat** [comment]
@ojnc we are Omicronlab. And, we made the Font Fixer too :smile:
