### ISSUE TITLE
ctrl+M minimizes safari browser

### ISSUE THREAD

**Issue by auninda** [torifat/jsAvroPhonetic#2]
Hello,
like my title says, ctrl+M shortcut needs to be changed as safari treats that shortcut for minimizing the browser.

auninda

**Comment by torifat** [comment]
In windows or mac?

**Comment by auninda** [comment]
well in windows. safari browser. i changed the keycode to a different key
to avoid the problem.

On Thu, Apr 12, 2012 at 4:23 PM, Rifat Nabi <
reply@reply.github.com

> wrote:
> 
> In windows or mac?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/torifat/jsAvroPhonetic/issues/2#issuecomment-5088245

## 

Auninda Rumy Saleque
Asst. System Programmer
Ayesha Abed Library
BRAC University
Dhaka, Bangladesh

**Comment by torifat** [comment]
Ok, its a problem then. We choose, because WikiPedia uses it (Ctrl+M). We wanted to go for a standard. I'm tagging Mehdi Bhai for further discussion.

@omicronlab

**Comment by auninda** [comment]
no problem :)

On 4/12/12, Rifat Nabi
reply@reply.github.com
wrote:

> Ok, its a problem then. We choose, because WikiPedia uses it (Ctrl+M). We
> wanted to go for a standard. I'm tagging Mehdi Bhai for further discussion.
> 
> @omicronlab
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/torifat/jsAvroPhonetic/issues/2#issuecomment-5094356

## 

Auninda Rumy Saleque
Asst. System Programmer
Ayesha Abed Library
BRAC University
Dhaka, Bangladesh
