### ISSUE TITLE
Can't write a few words

### ISSUE THREAD

**Issue by RatulSaha** [torifat/jsAvroPhonetic#7]
তোমার, ঠিক, শীত, যখন. Amazing tool, though! If you show how to commit these and subsequent changes, I would happy to.

**Comment by kaustavdm** [comment]
- তোমার = tOmar
- ঠিক = Thik
- শীত = sheet
- যখন = zokhon

does this help?

**Comment by RatulSaha** [comment]
Thanks a lot for the reply! I went through the js and finally found out the combinations and their replies.

Is their any plan to make it more interactive like Google Input tools? To start with, there can be initial grouping of possible combinations.

**Comment by kaustavdm** [comment]
There is already some work being done for porting Avro Phonetic to GNU/Linux using ibus. You can have a look at https://github.com/sarim/ibus-avro/. It uses jsAvroPhonetic as its parser and provides dictionary support. But it is meant for desktop users.

For the web, I'm sure we can work something out if Rifat bhai here puts in his help :smile:

**Comment by torifat** [comment]
@kaustavdm providing dictionary with the js library is not feasible. So, we have to create a web API for this, like google did. But, sadly we don't have enough architecture support to provide smooth API like google.

**Comment by RatulSaha** [comment]
Why not adding grouping of matched phrase instead of creating a dictionary?
For example, if I understand the JS correct, each group of keystroke is
almost uniquely represented to a unicode Bangla char set. Instead, why not
mapping them to a set of possible matches (and providing the options in a
dropdown) to help the users?

I will try to make a mockup in next few days.

**Comment by torifat** [comment]
@RatulSaha best of luck :+1:

**Comment by kaustavdm** [comment]
@torifat I was about to suggest the same thing as @RatulSaha. But performance will be an issue in this case, as the processing will be done on client side and slightly older browsers or machines with low memory can face issues when user types pretty fast. The same thing happens with ibus-avro at the present. To get around the issue, we can use a timeout like hoverintent does and trigger the regex search only after user has paused typing.

**Comment by torifat** [comment]
@kaustavdm @RatulSaha you guys can fork and do the experiments :smile:

**Comment by kaustavdm** [comment]
@torifat Don't think I will have time at the present :cry: I'll try a hand on it couple of weeks later.

**Comment by RatulSaha** [comment]
There are a few typewatcher functions available that can be attached as
well. They understand and predict when an user stopped typing. A usecase is
autocomplete.js for Drupal.

I would try to make the early mockup and see what the upperbound for the
possible combinations in a few days.

On Wed, May 22, 2013 at 11:01 PM, Kaustav Das Modak <
notifications@github.com> wrote:

> @torifat https://github.com/torifat Don't think I will have time at the
> present [image: :cry:] I'll try a hand on it couple of weeks later.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/torifat/jsAvroPhonetic/issues/7#issuecomment-18284443
> .

## 

Ratul Saha.
Student.
