### ISSUE TITLE
Cannot write bangla after updating to latest chrome 27.0.1453.93

### ISSUE THREAD

**Issue by masumsoft** [torifat/jsAvroPhonetic#8]
My OS: MacOSX Lion
Browser: Chrome 27.0.1453.93

The online version used to work perfectly before. But after chrome updated to the latest version, this no longer seems to work.

**Comment by torifat** [comment]
@masumsoft are you using the chrome extension? or anything else?

**Comment by masumsoft** [comment]
@torifat Nop, I'm using this online version here: http://torifat.github.io/jsAvroPhonetic/

**Comment by masumsoft** [comment]
it works on firefox, but not in chrome

**Comment by torifat** [comment]
Ok, I will fix it in this weekend. Thanks for reporting bro :)

**Comment by masumsoft** [comment]
Nice to know, you guys are doing an awesome job, keep it up bro :)
